### ISSUE TITLE
"Bin docker is not in your path" when using --runtime=containerd

### ISSUE THREAD

**Issue by stealthybox** [weaveworks/ignite#476]
@sbernheim ran into this bug with a Chromebook running Linux
(GalliumOS/xubuntu amd64)

He reports that we only had containerd installed.
This makes sense and should work without producing this error during `ignite run`:
```
INFO[0002] Created VM with ID "57f96e13460eb5df" and name "my-vm" 
FATA[0002] [ERROR ]: Bin docker is not in your PATH  
```
We may have missed this since we're always developing and testing on machines with both runtimes.

______________________
Full trace:
```bash
# ignite version
Ignite version: version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.2", GitCommit:"8222585fa9e5e72b0b44d007c3ea179d0066c03d", GitTreeState:"clean", BuildDate:"2019-10-08T03:53:06Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.18.0
Runtime: containerd

# ignite run --runtime containerd --log-level trace --config my-vm.yaml
TRAC[0000] Populating providers...                      
TRAC[0000] Initializing the containerd runtime provider... 
TRAC[0000] Initializing the CNI provider...             
DEBU[0000] Ensuring image weaveworks/ignite-ubuntu:latest exists, or importing it... 
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] index: counted 0 Image object(s)             
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] cache: Get Image with UID "1d9a607b2184e0ed" 
TRAC[0000] index: cache miss for Image with UID "1d9a607b2184e0ed" 
TRAC[0000] index: storing Image object with UID "weaveworks/ignite-ubuntu:latest", meta: false 
DEBU[0000] Found image with UID 1d9a607b2184e0ed        
DEBU[0000] Ensuring kernel weaveworks/ignite-kernel:4.19.47 exists, or importing it... 
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel 
TRAC[0000] index: counted 0 Kernel object(s)            
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel 
TRAC[0000] cache: Get Kernel with UID "4d87e839eb5f09ed" 
TRAC[0000] index: cache miss for Kernel with UID "4d87e839eb5f09ed" 
TRAC[0000] index: storing Kernel object with UID "weaveworks/ignite-kernel:4.19.47", meta: false 
DEBU[0000] Found kernel with UID 4d87e839eb5f09ed       
TRAC[0000] index: counted 0 VM object(s)                
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=VM 
TRAC[0000] index: counted 0 VM object(s)                
TRAC[0000] cache: miss when listing: ignite.weave.works/__internal, Kind=VM 
TRAC[0000] Client.Set; UID: "57f96e13460eb5df", GVK: ignite.weave.works/__internal, Kind=VM 
TRAC[0000] cache: Set VM with UID "57f96e13460eb5df"    
TRAC[0000] index: storing VM object with UID "my-vm", meta: false 
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] index: counted 1 Image object(s)             
TRAC[0000] cache: hit when listing: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] index: listing ignite.weave.works/__internal, Kind=Image objects, meta: true 
TRAC[0000] cacheObject: "weaveworks/ignite-ubuntu:latest" checksum: "1570727891432058185" 
TRAC[0000] cache: Get Image with UID "1d9a607b2184e0ed" 
TRAC[0000] index: cache hit for Image with UID "1d9a607b2184e0ed" 
TRAC[0000] cacheObject: "weaveworks/ignite-ubuntu:latest" checksum: "1570727891432058185" 
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] index: counted 1 Image object(s)             
TRAC[0000] cache: hit when listing: ignite.weave.works/__internal, Kind=Image 
TRAC[0000] index: listing ignite.weave.works/__internal, Kind=Image objects, meta: true 
TRAC[0000] cacheObject: "weaveworks/ignite-ubuntu:latest" checksum: "1570727891432058185" 
TRAC[0000] cache: Get Image with UID "1d9a607b2184e0ed" 
TRAC[0000] index: cache hit for Image with UID "1d9a607b2184e0ed" 
TRAC[0000] cacheObject: "weaveworks/ignite-ubuntu:latest" checksum: "1570727891432058185" 
TRAC[0000] Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel 
TRAC[0000] index: counted 1 Kernel object(s)            
TRAC[0000] cache: hit when listing: ignite.weave.works/__internal, Kind=Kernel 
TRAC[0000] index: listing ignite.weave.works/__internal, Kind=Kernel objects, meta: true 
TRAC[0000] cacheObject: "weaveworks/ignite-kernel:4.19.47" checksum: "1570729004007891923" 
TRAC[0000] cache: Get Kernel with UID "4d87e839eb5f09ed" 
TRAC[0000] index: cache hit for Kernel with UID "4d87e839eb5f09ed" 
TRAC[0000] cacheObject: "weaveworks/ignite-kernel:4.19.47" checksum: "1570729004007891923" 
INFO[0002] Created VM with ID "57f96e13460eb5df" and name "my-vm" 
FATA[0002] [ERROR ]: Bin docker is not in your PATH     
```

**Comment by till** [comment]
@stealthybox Can you re-open this bug?

---

```
root@Ubuntu-1804-bionic-64-minimal ~ # ignite version
Ignite version: version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.3", GitCommit:"ed51b9378f6e0982461074734beb145d571d56a6", GitTreeState:"clean", BuildDate:"2019-12-10T06:19:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Firecracker version: v0.18.1
Runtime: containerd
root@Ubuntu-1804-bionic-64-minimal ~ # ignite start my-vm --runtime containerd
FATA[0000] [ERROR ]: Bin docker is not in your PATH
```

**Comment by bbros-dev** [comment]
We observed this error with and without `--runtime containerd`.  The use case is test-kitchen suites where we are certain docker is not installed - and won't be.

**Comment by till** [comment]
@bbros-dev I forgot to comment, it seems like "docker-cli" is always needed? The docs are a little confusing, as one of them doesn't mention it. Maybe @chanwit can comment if this is a doc bug or something else.

**Comment by bbros-dev** [comment]
Thanks @till.
Standing by - @chanwit we are setting up Ubuntu following [these instructions](https://ignite.readthedocs.io/en/stable/installation.html#installing-dependencies).

**Comment by till** [comment]
@bbros-dev yeah, I got confused by this as well. And then read this, it mentions `docker`:
https://ignite.readthedocs.io/en/stable/dependencies.html

**Comment by till** [comment]
@bbros-dev I published my _WIP_ Ansible to setup ignite nodes: https://github.com/Luzilla/ansible-ignite

**Comment by bbros-dev** [comment]
Thanks @till for sharing, our cookbook is [here](https://github.com/BegleyBrothers/cookbook-ignite/tree/develop), `develop` branch, but still not working.

Was _really_ hoping to keep docker cruft off our systems - seems not yet.
